# Guide Pratique Pandas : Manipulation des Lignes et Colonnes

Ce notebook présente les manipulations fondamentales sur un DataFrame Pandas :
1. **Trier les colonnes** (ordre alphabétique / custom)
2. **Sélectionner une colonne** (Series vs DataFrame)
3. **Éliminer une colonne** (`drop`)
4. **Sélectionner et exclure des lignes** (`loc`, `iloc`, filtrage booléen)
5. **Cas pratique récapitulatif**

## 0. Initialisation et Jeu de Données d'Exemple

In [1]:
import pandas as pd

# Création d'un DataFrame de test non trié
data = {
    'Salaire': [45000, 62000, 38000, 54000, 71000],
    'Age': [29, 41, 23, 35, 52],
    'Nom': ['Alice', 'Bob', 'Charlie', 'Diane', 'Éric'],
    'Ville': ['Paris', 'Lyon', 'Marseille', 'Lille', 'Bordeaux'],
    'Departement': ['IT', 'Finance', 'RH', 'IT', 'Direction']
}

df = pd.DataFrame(data, index=['id_101', 'id_102', 'id_103', 'id_104', 'id_105'])
print("--- DataFrame Initial ---")
df

--- DataFrame Initial ---

        Salaire  Age      Nom      Ville Departement
id_101    45000   29    Alice      Paris          IT
id_102    62000   41      Bob       Lyon     Finance
id_103    38000   23  Charlie  Marseille          RH
id_104    54000   35    Diane      Lille          IT
id_105    71000   52     Éric   Bordeaux   Direction

## 1. Trier les Colonnes

On peut réordonner les colonnes :
- Par ordre alphabétique via `.sort_index(axis=1)`
- Selon un ordre personnalisé en passant une liste

In [2]:
# 1.1 Tri alphabétique croissant
df_tri_alpha = df.sort_index(axis=1)
print("Colonnes triées par ordre alphabétique croissant :")
df_tri_alpha

Colonnes triées par ordre alphabétique croissant :

        Age Departement      Nom  Salaire      Ville
id_101   29          IT    Alice    45000      Paris
id_102   41     Finance      Bob    62000       Lyon
id_103   23          RH  Charlie    38000  Marseille
id_104   35          IT    Diane    54000      Lille
id_105   52   Direction     Éric    71000   Bordeaux

In [3]:
# 1.2 Tri alphabétique décroissant
df_tri_desc = df.sort_index(axis=1, ascending=False)
print("Colonnes triées par ordre alphabétique décroissant :")
df_tri_desc

Colonnes triées par ordre alphabétique décroissant :

            Ville  Salaire      Nom Departement  Age
id_101      Paris    45000    Alice          IT   29
id_102       Lyon    62000      Bob     Finance   41
id_103  Marseille    38000  Charlie          RH   23
id_104      Lille    54000    Diane          IT   35
id_105   Bordeaux    71000     Éric   Direction   52

In [2]:
# 1.3 Réorganisation manuelle selon un ordre précis
ordre_voulu = ['Nom', 'Age', 'Departement', 'Ville', 'Salaire']
df_reordonne = df[ordre_voulu]
print("Colonnes réordonnées manuellement :")
df_reordonne

Colonnes réordonnées manuellement :

            Nom  Age Departement      Ville  Salaire
id_101    Alice   29          IT      Paris    45000
id_102      Bob   41     Finance       Lyon    62000
id_103  Charlie   23          RH  Marseille    38000
id_104    Diane   35          IT      Lille    54000
id_105     Éric   52   Direction   Bordeaux    71000

## 2. Sélectionner une Colonne

- Simple crochet `df['Nom']` : renvoie un objet **`pd.Series`** (1D)
- Double crochet `df[['Nom']]` : renvoie un **`pd.DataFrame`** (2D)
- Sélection par attribut `df.Nom` (valide si le nom n'a pas d'espace ni de conflit avec les méthodes pandas)

In [3]:
# Sélection simple -> Series
col_series = df['Nom']
print("Type :", type(col_series))
print(col_series)

Type : <class 'pandas.core.series.Series'>
id_101      Alice
id_102        Bob
id_103    Charlie
id_104      Diane
id_105       Éric
Name: Nom, dtype: object

In [4]:
# Sélection double crochets -> DataFrame
col_df = df[['Nom']]
print("Type :", type(col_df))
col_df

Type : <class 'pandas.core.frame.DataFrame'>

            Nom
id_101    Alice
id_102      Bob
id_103  Charlie
id_104    Diane
id_105     Éric

## 3. Éliminer une Colonne

On utilise `.drop()` en spécifiant `columns=['...']` (recommandé) ou `axis=1`.

In [5]:
# Supprimer une seule colonne (retourne un nouveau DataFrame)
df_sans_ville = df.drop(columns=['Ville'])
print("DataFrame sans la colonne 'Ville' :")
df_sans_ville

DataFrame sans la colonne 'Ville' :

        Salaire  Age      Nom Departement
id_101    45000   29    Alice          IT
id_102    62000   41      Bob     Finance
id_103    38000   23  Charlie          RH
id_104    54000   35    Diane          IT
id_105    71000   52     Éric   Direction

In [8]:
# Supprimer plusieurs colonnes en une seule opération
df_light = df.drop(columns=['Ville', 'Departement'])
print("DataFrame sans 'Ville' ni 'Departement' :")
df_light

DataFrame sans 'Ville' ni 'Departement' :

        Salaire  Age      Nom
id_101    45000   29    Alice
id_102    62000   41      Bob
id_103    38000   23  Charlie
id_104    54000   35    Diane
id_105    71000   52     Éric

## 4. Sélectionner une Ligne et en Exclure une Autre

Il existe 3 approches selon le besoin :
1. **Par label** (`.loc`)
2. **Par position entière** (`.iloc`)
3. **Par condition booléenne** (masque)

In [11]:
# 4.1 Sélection par label d'index (.loc)
# Sélectionner 'id_101' et 'id_103' (en ignorant 'id_102')
selection_loc = df.loc[['id_101', 'id_103']]
print("Lignes sélectionnées par index : ", selection_loc)

# Exclure explicitement une ligne avec drop
df_sans_102 = df.drop(index='id_102')
print("DataFrame sans la ligne 'id_102' :", df_sans_102)

Lignes sélectionnées par index :          Salaire  Age      Nom      Ville Departement
id_101    45000   29    Alice      Paris          IT
id_103    38000   23  Charlie  Marseille          RH
DataFrame sans la ligne 'id_102' :         Salaire  Age      Nom      Ville Departement
id_101    45000   29    Alice      Paris          IT
id_103    38000   23  Charlie  Marseille          RH
id_104    54000   35    Diane      Lille          IT
id_105    71000   52     Éric   Bordeaux   Direction

In [12]:
# 4.2 Sélection par position (.iloc)
# Prendre la première ligne (index 0) et la troisième (index 2), exclure la deuxième (index 1)
selection_pos = df.iloc[[0, 2]]
print("Lignes aux positions 0 et 2 :")
selection_pos

Lignes aux positions 0 et 2 :

        Salaire  Age      Nom      Ville Departement
id_101    45000   29    Alice      Paris          IT
id_103    38000   23  Charlie  Marseille          RH

In [15]:
# 4.3 Sélection / Exclusion par condition logique
# Sélectionner toutes les lignes SAUF celle où Nom == 'Bob'
df_sans_bob = df[df['Nom'] != 'Bob']
print("DataFrame sans Bob : ", df_sans_bob)

# Sélectionner les profils avec Salaire > 50000 ET Departement != 'Direction'
df_condition = df[(df['Salaire'] > 50000) & (df['Departement'] != 'Direction')]
print("Salariés > 50k hors Direction :", df_condition)

DataFrame sans Bob :          Salaire  Age      Nom      Ville Departement
id_101    45000   29    Alice      Paris          IT
id_103    38000   23  Charlie  Marseille          RH
id_104    54000   35    Diane      Lille          IT
id_105    71000   52     Éric   Bordeaux   Direction
Salariés > 50k hors Direction :         Salaire  Age    Nom  Ville Departement
id_102    62000   41    Bob   Lyon     Finance
id_104    54000   35  Diane  Lille          IT

## 5. Synthèse & Enchaînement (Method Chaining)

Toutes ces étapes peuvent être chaînées en une seule transformation fluide et lisible :

In [16]:
resultat = (
    df
    .drop(columns=['Ville'])             # 1. Éliminer une colonne
    .sort_index(axis=1)                 # 2. Trier les colonnes alphabétiquement
    .loc[lambda d: d['Nom'] != 'Bob']   # 3. Exclure la ligne 'Bob'
)

print("--- Résultat du Pipeline ---")
resultat

--- Résultat du Pipeline ---

        Age Departement      Nom  Salaire
id_101   29          IT    Alice    45000
id_103   23          RH  Charlie    38000
id_104   35          IT    Diane    54000
id_105   52   Direction     Éric    71000